name: Build App (iOS & Android)

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: preview

  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: preview
